### ISSUE TITLE
Add host/organiser column at GDCR events listing

### ISSUE THREAD

**Issue by erorcodes** [coderetreat/coderetreat.org#215]
In the listing there is a column for facilitator, and for sponsor. However there are not one for the organiser, which not necessary is the same as the sponsor or facilitator. This would be nice to have!

**Comment by erorcodes** [comment]
Would love to contribute to this implementation if the "feature" is desirable

**Comment by rradczewski** [comment]
Good point @erorcodes 🤔 we called it moderators in the schema, I understand both hosts and facilitators as moderators, but the column says "facilitators". 

The only reasonable solution I see (I couldn't tell facilitators from hosts in that list) is to rename the column to "Hosts & Facilitators".

What do you think?

**Comment by erorcodes** [comment]
Yeah, just renaming the column is the most simple solution =) 

I did a suggestion for an added column, but not sure it is correctly implemented, should I open a pull request?

**Comment by erorcodes** [comment]
The added column could be used for next year also, not merging it now. There are a couple of other things around that I'd like to discuss and try implementing =) But that could be in another issue if we want to separate things.
