### ISSUE TITLE
What about automatically updating the site (days left to next event, etc.) every 1st of January?

### ISSUE THREAD

**Issue by thodorisbais** [coderetreat/coderetreat.org#265]

**Comment by tpd-opitz** [comment]
*automatically updating the days left to next event every 1st of January* would imply an *automatically scheduling of the event*. I think there are other then technical implications to be considered too.

**Comment by Erdbeervogel** [comment]
Hey Thomas, thanks for your idea. What were you envisioning specifically? 

Finding the next date for the next GDCR involves checking with some of the global communities about any events they have scheduled for any weekends towards the end of the year and any holidays, too. So it's hard to automate this. 

But keen to understand and learn more about your idea so we might be able to do something if it works with the above constraint.

**Comment by tpd-opitz** [comment]
@Erdbeervogel 
An automatical calculation of "days left to next event" implies that the "next event" is in future. In the last years the new date for the GDCR was fixed rather late in april or june. So the functionality must deactivate itself until the new date is scheduled.
