### ISSUE TITLE
More / better integration for video calls (empty rooms, cycling through rooms, making dates and arrangements)

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/coderetreat.org#269]
The platform should have a public app that allows us....

- to query the number of people in a given room
- to join a room

**Comment by jdvr** [comment]
Further reading: 
https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md#controlling-the-embedded-jitsi-meet-conference

**Comment by jdvr** [comment]
This [API](https://github.com/jitsi/jitsi-meet/blob/cd910e3074d6631e05d5a4dd52c3085f08303373/doc/cloud-api.swagger) allows us to create conferences rooms but I haven'f find anyway of query room number of members.

Some workaround:

1. Find a way to query the `xmpp` server using `http-bind` endpoint
2. ¿crawler?
3. ... WIP

**Comment by jdvr** [comment]
There is a request to api.appear.in _(https://api.appear.in/organizations/1/room/any-room)_ that seems very easy to replicate but.. it requires a authorization header with a basic token.

**Comment by jdvr** [comment]
I have created a simple code to iteract with api.appear.in but  I am experimenting a `CORS`error.
```js
