### ISSUE TITLE
Schedule tweets with blogposts about coderetreats

### ISSUE THREAD

**Issue by mplavcan** [coderetreat/coderetreat.org#270]
- gather a list of blogposts (we had one a couple of years ago)

**Comment by rradczewski** [comment]
We host [some blogposts](http://coderetreat.org/pages/blog/) on our own, but there might be more out there, in particular from [Adi](http://blog.adrianbolboaca.ro/category/coderetreat/) or [Alex](http://www.alexbolboaca.ro/category/coderetreat), but also one like [this by Corey](http://blog.coreyhaines.com/2011/01/on-goals-of-coderetreat.html).

Tweets could be scheduled, e.g. as a Throwback Thursday, using TweetDeck, Hootsuite or Buffer

**Comment by thodorisbais** [comment]
As of 13-03-2018, it was agreed that the tweets should also include creditability.
Example: [super-cool-description-about-the-tweet by @twitterHandltOfTheAuthorOfThePost]

**Comment by thodorisbais** [comment]
Blog posts tweeted so far:

- [The Coderetreat Problem Is Not The Problem](http://www.alexbolboaca.ro/coderetreat/the-coderetreat-problem-is-not-the-problem)
- [Coderetreat: The toughest constraint](http://blog.adrianbolboaca.ro/2014/11/coderetreat-toughest-constraint/)
