### ISSUE TITLE
Improving the landing page so that potential community members know they're at the right place

### ISSUE THREAD

**Issue by c089** [coderetreat/coderetreat.org#390]
I never noticed this before, but here's a screenshot of the visible section when landing of coderetreat.org in a maximized browser window on my 15" MacBook:

<img width="600" alt="screenshot 2018-10-18 at 13 17 36" src="https://user-images.githubusercontent.com/327199/47151268-8e2f4980-d2d9-11e8-9a29-d6bb67f1754b.png">

I frequently encourage people to join a coderetreat and I just realized this may not be the most welcoming experience for new people. With the big call to action to register my own event and no event on the map above the fold (yet... what's up, cold places? :D), at first I might think "this is not the page I'm looking for, it's just for the organizers".

Maybe we could put the one-line definition / pitch in a central section above the fold, and have two equal links to sections of the site for guests and organizers?

**Comment by rachelcarmena** [comment]
Hi @c089,

Thanks for the idea!! :clap: Please, could you visit the webpage again?

Please, let us know about this issue after visiting it again. A lot of made changes and more of them in the backlog!! :wink: 

Thanks!!
