### ISSUE TITLE
list "mid term events"

### ISSUE THREAD

**Issue by tpd-opitz** [coderetreat/coderetreat.org#472]
Old website allowed us to announce events at other dates then the official GDCR. All GDCR events were identified by a tag.

I'd like to get back the "mid term events" list. 

Maybe we can collect them in a separate folder `/data/upcomming_events/` adding a `date` field to the JSON template. (could be helpfull to fail the build when the given date matches the next GDCR. Existing events might be moved when the next GDCR is announced)

In the world map I'd like to see all future "upcomming" events at other date then the next GDCR with a different color. 
We might need some kind of "job" to delete events after their due date or display them in red...

**Comment by mplavcan** [comment]
Interim events are now supported!:  Arbitrary dates and listing are in place.
Advertising and listing is still rudimentary, but improvements are near the top of the feature backlog.

We've removed the world map, as prevalence of virtual events have made the timezone more important/prevalent.
