### ISSUE TITLE
Hosting next Coderetreat 2020

### ISSUE THREAD

**Issue by jjdelcampo** [coderetreat/coderetreat.org#694]
Hi there, 
We're interested in hosting 2020 Global Coderetreat. We're based in Madrid (Spain).
Please, let us know what are the next steps to take (related to the hoster list). We'll be in touch through the slack channel as well (Juan José del Campo).
Thanks in advance,
Juanjo

**Comment by rradczewski** [comment]
Hi @jjdelcampo,

we launched our process of listing your event (similar to the ones we used in the last year). The process is described on our [Register Your Event](https://www.coderetreat.org/facilitators/register/) page.

Please let us know if you encounter any issues, we acknowledge that you're being our alpha tester in this :-)
